000 ---	FROM DATE CANNOT BE AFTER TO DATE.
001 ---	LEAVE REQUEST SUBMITTED SUCCESSFULLY!
002 ---	LEAVE REQUEST CLEARED.
003 ---	PLEASE ENTER ALL REQUIRED FIELDS.
004 ---	ERROR SAVING LEAVE REQUEST.
005 ---	EMPLOYEE NUMBER NOT FOUND